### ISSUE TITLE
unit / bottom type(s): null / undefined

### ISSUE THREAD

**Issue by dckc** [ocapn/ocapn#50] opened 2023-05-17 18:17 UTC
In https://github.com/ocapn/ocapn/issues/5#issue-859797863 @cwebber wrote:
> Void (equivalent to "undefined")

@erights 23 Apr https://github.com/ocapn/ocapn/issues/5#issuecomment-826029525
> I'm going to insist on two bottom values, which we can call null and undefined.

@zenhack 
> I am very antagonistic to baking in both undefined and null as a primitives, and I think it would be better to encode this as a tag. I think being able to describe undefined without inventing a one-off type is also a good test case for whether the data model is likely to be flexible enough to handle the curveballs in the types provided by $LANGUAGE as well.

@erights
> it is fine with me to use a tag for undefined.

**Comment by erights** [comment] 2023-05-17 20:47
That would no longer be fine with me. If that's a blocker, we need to discuss. From @zenhack 's recent posts, it seems it is not a blocker for @zenhack .

**Comment by dckc** [comment] 2023-05-17 21:07
taking the liberty of assigning this to @cwebber and @tsyesika  - we have input from capn-proto and Agoric but I haven't found record of Spritely being OK with both `null` and `undefined`.

**Comment by zenhack** [comment] 2023-05-17 22:12
Quoting Mark S. Miller (2023-05-17 16:47:58)

>    That would no longer be fine with me. If that's a blocker, we need to
>    discuss. From ***@***.*** 's recent posts, it seems it is not a blocker
>    for ***@***.*** .

It's not a blocker for me.

**Comment by cwebber** [comment] 2023-05-18 18:20
As said, I think two bottom types is bizarre... I can't imagine wanting to include them from a "this is a good design" perspective at all, only from a "this is what the JS world currently does" perspective.  I am willing to concede to it if it provides interoperability, as @tsyesika says.

However, it would be helpful to understand what caused:

> That would no longer be fine with me.

What changed in your perspective, @erights?  We should at least have a semantic understanding of the reason, for the record.

**Comment by dckc** [comment] 2023-05-18 18:31
This issue is resolved to my satisfaction: `null` and `undefined` are distinct OCapN values, and they are distinct from all other OCapN values.

The specification in https://github.com/ocapn/ocapn/issues/3#issuecomment-1552187671 seems adequate:

```capnp
# ocapn.capnp
@0xcd301da1d95b8242;

struct Value {
  union {
    ## Atoms ##

    undefined @0 :Void;
    null @1 :Void;
    bool @2 :Bool;
    ...
```

Let's try the "close it and see if it sticks" process, subject to appeal at the next meeting (#43). @jar398 Please note this at that meeting and ask whether anyone wants to reconsider.

**Comment by dckc** [comment] 2023-05-18 19:54
oops... I missed https://github.com/ocapn/ocapn/issues/50#issuecomment-1553444102

The request for rationale seems worth pursuing.

**Comment by erights** [comment] 2023-05-21 01:07
Historical background, context for rationale first:

I said 
> In particular, it is fine with me to use a tag for `undefined`.
at
https://github.com/ocapn/ocapn/issues/5#issuecomment-826031782
in April 2021.

Inspired by the ocapn discussions of tagging as an extension point, and running into problems trying to define too much of our `marshal` package at one level, at some point I introduced the `Tagged`. Due to my non-fluency with github, the closest I was able to track that down is https://github.com/endojs/endo/pull/982 from Jan 2022. However, that says it was a port from an earlier fork that has since been deleted. In any case, by Jan 2022 `Tagged` had essentially its current form.

By that date, `Passable` had also settled down into a taxonomy that includes `undefined` as a primitive, and therefore `Tagged` as not including an encoding of that primitive.

Rationale:

Having introduced a basic taxonomy of distinct passable values which includes `Tagged`, we necessarily have a system with at least two levels of tagging. Any encoding needs some kind of tag in the representation to distinguish numbers from strings, for example. This is implicit in the proposed data model, but will clearly happen somehow in any encoding. Explicit in the data model is the second level of tagging, the `Tagged`.

Agoric needs an `undefined` to round trip back to us as an `undefined`. Agoric needs a `Tagged` to round trip back to us as a `Tagged`. If someone builds an encoding whose first level tagging does not make all the distinctions of our data model, instead relying of some kind of tagging for the rest, that is fine. The distinctions of the rest of the data model can rest on this second level of tagging. In fact, smallcaps can be described in this manner. However, that second level of tagging cannot absorb the `Tagged`. The tagging of `Tagged` would have to be a third level of tagging. Again, smallcaps can be described in these terms.

I do not think our ocapn data model should distinguish the first two levels of such a three level scheme. In this regard, I think the current draft data model has it exactly right.

**Comment by erights** [comment] 2023-05-21 01:09
AFAIK, this rationale was the only remaining reason this issue was open. So, closing.

**Comment by erights** [comment] 2023-05-21 01:10
Ah, I do not seem to have the power to close. Someone who does, please close this.

**Comment by dckc** [comment] 2023-05-21 02:56
It's still not clear to me why Agoric can't map `undefined` to OCapN `Tagged` and back, if we reserve the tag 'undefined' on both ends for this purpose:

in `passable.toOcapn()`: `if (x === undefined) return ocapn.makeTagged('undefined'); if (isTagged(x)) { return ocapn.makeTagged(getTag(x), x.payload)`
in `passable.fromOCapn()`: `if (ocapn.isTagged(x) && x.tag === 'undefined') { return undefined } else { return makeTagged(x.tag, x.value) };`

This round-trips every passable `Tagged` as well as `undefined`.

`'undefined'` would never be used as a passable tag; it would only be reserved to avoid some hilbert encoding of `makeTagged('undefined', payload)`.

I'm reasonably confident a similar arrangement would work for symbols.

Perhaps the point is: we could, but at the cost of a tree-walk for every crossing. We're going to have a tree walk for every crossing anyway, though, for serialization / unserialization.

So the justification to me looks like: we could demote `undefined` to an OCapN Tagged, but it would be a hassle for Agoric and nobody minds it as 1st class too much. (Same justification seems to apply for symbols.) Looks like standards fatigue already.

But again, I don't feel strongly enough about it to keep this open.

**Comment by erights** [comment] 2023-05-21 04:43
> if we reserve the tag 'undefined' on both ends for this purpose:

It is way too late for us to be able to consider that. (That's why I started with the historical note. We do not have the flexibility we may have had in 2021.) 

At the `@endo/pass-style` and `@endo/marshal` levels of abstractions, Taggeds are recognized, rank-ordered, and sorted but uninterpreted. They are interpreted only by `@endo/patterns`. `undefined` must be distinguished by `@endo/pass-style`. Recognition of particular kinds of `Tagged`s is not required to be universal. Unrecognized `Tagged`s must still round trip.

**Comment by erights** [comment] 2023-05-21 04:48
> I'm reasonably confident a similar arrangement would work for symbols.

I am very interested in seeing a concrete proposal for this. We need it. Our current use of symbols in the protocol is so light (only `Symbol.asyncIterator` so far) that we can still likely be flexible.

**Comment by erights** [comment] 2023-05-21 04:53
> Looks like standards fatigue already.

What do you mean by "standards fatigue"?

**Comment by dckc** [comment] 2023-05-21 06:05
> It is way too late for us to be able to consider that.

It's too late to consider not using the string-tag `'undefined'`? That's the only change to `@endo/pass-style` or `@endo/marshal` that I was contemplating.

I did _not_ suggest that `@endo` use an endo `Tagged` to represent `undefined`. Only that when passables are converted to ocapn values, `undefined` could be represented as an ocapn Tagged.

> What do you mean by "standards fatigue"?

It's an anti-pattern where rather than being diligent to keep a spec minimal on behalf of all the eventual users of the tech, we just go "oh well. it's not that big of a deal to just let this in."

Coincidentally, the first time I saw your name was in 2001 when Aaron Swartz noted your [smallstd.org](https://web.archive.org/web/20020125220155/http://smallstd.org/) work: "The world is filling up with bloated standards designed and expanded by committees run amok, as with XML and the w3c."

https://chatlogs.planetrdf.com/rdfig/2001-09-05.html#T18-02-29

**Comment by zenhack** [comment] 2023-05-21 17:31
I'm going to re-open this; it seems like it's not actually settled, or at a minimum we still have some things to discuss to understand why we're stuck with this.

**Comment by dckc** [comment] 2023-05-21 20:06
Odds are better than even that I've misunderstood MarkM's position. We'll see...

**Comment by zenhack** [comment] 2023-05-21 21:33
I'm sure this has been explained in some prior discussion, but can someone link to/reproduce an explanation of what each `@endo/*` layer does?

I'm not 100% sure, but what it sounds like Mark is that the issue is that agoric has an order defined (not sure whether it's total or partial) on data at a lower-level of abstraction than the layer that interprets `Tagged`s, and that that if `undefined` were the same as e.g. `makeTagged('undefined', null)` it would be in the wrong spot in that order.

Do I have that right? If so, what exactly breaks if this order is changed?

**Comment by erights** [comment] 2023-05-21 22:18
I am making many arguments. Each is about an additional pain point. None by themselves is fatal. The ordering properties by themselves are one of these non-fatal issues. I will explain about layering and ordering at the upcoming meeting.

A bigger pain point would be the explanatory cost: ***"An OCapN `Tagged` is a JS `Tagged` unless the OCapN tag name is `'undefined'`, in which case it is a JS `undefined`."*** Just no. No, on the same grounds on which Christine rejected the omission of symbols. Again, by itself, this is a non-fatal issue. But it would contribute to death by a thousand cuts.

Shannon showed bits were a universal representation language, in which all others could be encoded. If all we're doing is inventing arbitrarily painful ways to encode into the common medium of bits, well, bits are already an adequate standard. We're also trying to narrow the semantic gap between each of our systems and the standard we're trying to negotiate. Otherwise, what's the point?

Why am I unable to close this issue? Could someone give me the required permissions? Thanks.

**Comment by erights** [comment] 2023-05-21 22:38
Btw, if we were stuck having to cope with only one OCapN bottom type, we'd map JS `undefined` to that type, and find some other way to encode the JS `null`. (Not that we would consider that either. But stating it to be clear. It would be the much less painful option for us.)

**Comment by jar398** [comment] 2023-05-21 23:22
@erights You should have appropriate permissions now (github 'Write' role in repo). Let me know if permissions don't seem right now.

**Comment by erights** [comment] 2023-05-21 23:25
@jar398 thanks!

Closing, with two bottom values: Null and Undefined.

Please reopen only if we really need to revisit this decision. Thanks.

**Closed by erights** 2023-05-21 23:25 UTC

**Comment by zenhack** [comment] 2023-05-22 04:17
Quoting Mark S. Miller (2023-05-21 18:18:34)

>    A bigger pain point would be the explanatory cost: "An OCapN Tagged is
>    a JS Tagged unless the OCapN tag name is 'undefined', in which case it
>    is a JS undefined." Just no. No, on the same grounds on which Christine
>    rejected the omission of symbols. Again, by itself, this is a non-fatal
>    issue. But it would contribute to death by a thousand cuts.

This seems to fundamentally call in to question the value of including
Tagged at all: my understanding has been that the entire point is to
provide a way to extend the data types so that not everything anyone
might want needs to be either included in the raw data. If using them to
translate special js-native types isn't acceptable, what are they for?

Fwiw, I feel like it is fair to also push a bit harder on why using
Tagged to encode symbols is unacceptable, and given the above point of
the confusion, maybe also actually fruitful: I didn't do so at the time
because I don't actually have strong opinions about symbols, but is
there actually a technical reason why it would be problematic to encode
them as Taggeds with a label of "symbol" and a value of that symbol
encoded as a string?

I think hashing out what `Tagged` is for and what it can & can't do for
us is probably actually more important than than either of these
immediate questions of inclusion.

**Comment by zenhack** [comment] 2023-05-22 05:56
I moved my question about tagged to its own issue (#52); I don't care all that much about null/undefined in particular, but I think the fact that it doesn't seem to be covering the kinds of things that at least I thought it was supposed to merits discussion in its own right.

**Comment by erights** [comment] 2023-05-26 07:00
I realized something about my abhorrence of @dckc 's proposal above. If the JS `Tagged` does not include `undefined` and the OCapN `Tagged` does include `undefined`, then they are different concepts and need to have different names. Part of the strength of my reaction, I realize, came from using the same name to mean these two different things, which would cause all that explanatory pain.

This doesn't change my conclusion in this case. But I point it out because it may help clarify future such controversies. If the distinct concepts had two separate names, it would be clearer that the irreducible cost would be that we'd have two separate concepts rather than one. But at least we would avoid the cost of confusing one concept for the other.

"Similar things should be made the same or very different" --Alan Kay

One of my favorite Kay quotes. My slight refinement:

Similar things should be factored into the parts that are the same and the parts that are very different.

That perhaps better explains why my conclusion remains unchanged. These two separate concepts are still similar in the way that Kay complains about.

**Comment by zenhack** [comment] 2023-05-26 16:58
I think that also articulates well the reasons folks don't like having both null and undefined in the first place. But it is what it is.

**Comment by dckc** [comment] 2023-05-26 18:32
touche!

**Comment by erights** [comment] 2023-05-26 18:33
Agreed! I have hated having both since I first encountered JS!

**Comment by dpwiz** [comment] 2023-06-17 11:30
How come something like `undefined` can even be posted on a wire? As I understand, If something is "undefined", then you don't have it and shouldn't be able to send it anywhere.

> -- Here's your serialized nothing. Have fun exploding in at runtime.
> -- Thanks! Will do!

**Comment by jar398** [comment] 2023-07-05 17:13
Good question. If I had to guess: anything in the data model has to be post-able, and `undefined` has to be in the data model?  But it would be nice to know why both of these.

**Comment by kriskowal** [comment] 2023-09-18 06:18
@erights It would be good if this discussion could include a link to or summary of why Agoric needs to entrain both null and undefined in passable types. I’ve forgotten and had hoped to find it here, based on the topic.

My understanding is that we consider `undefined` to be the real bottom of JS types and `null` to be the unignorable wart. In a preliminary [rosetta masonry meeting](https://github.com/ocapn/ocapn/discussions/86) the general preference is toward uniformly favoring one of the bottom types (JavaScript `undefined`, Guile `*unspecified*`, Python `None`) and (given that Agoric insists) translate JavaScript `null` to a contrived and identity imported from `ocapn` in Guile and Python, tentatively `zilch` or `jsnull` in Guile (or something equally awful and difficult to confuse for elisp’s distinct flavor of `null`) and `Null` in Python.

We also come out of this meeting with a good understanding of how we represent these two bottom types mechanically, regardless of the concrete encoding. The salient consideration is that all of the concrete forms have two kinds of tagging: those that close the gap between the paucity of either JSON or Syrup and the expressiveness of CapTP “passable” types, and then “user” tags. The OCapN/Syrup implementation as written today has a special record label `<user-record...>` for these user tags, and Agoric has analogous pass-style=tagged objects out of which patterns and comparable complex immutable data strucutures emerge as potential OCapN conventions. So, in Syrup, both bottom types would be represented as records underneath the ocapn abstraction, e.g., `<void>` and `<null>`, literally `<4"void>` and `<4"null>`. In smallcaps these are currently `"#undefined"` and `null`. In compact ordered, these are currently `v` and `z`. Regardless, these values cannot be forged from user records or tags outside CapTP.

I’m sure regardless of the motivations for keeping `null`, my hope is that it is born deprecated and we discover that it’s more harmful than helpful quickly!

**Comment by erights** [comment] 2023-09-18 08:11
The problem with using Syrup Records is that OCapN Taggeds are also encoded as Syrup Records and OCapN Tagged need to round trip as distinct from OCapN Null or Undefined.

> I’m sure regardless of the motivations for keeping `null`, my hope is that it is born deprecated and we discover that it’s more harmful than helpful quickly!

I am happy to consider it born deprecated!

**Comment by erights** [comment] 2023-09-18 08:14
In short, the main reason I do not want to keep OCapN Null distinct from OCapN Undefined is
- for normal JS distributed object use, we want to use JS `undefined` as the normal bottom
- it would be awkward not to be able to round trip JSON data. It would also be awkward to have the mapping of JSON data to JS be different than the canonical mapping of JSON data to JS.

**Comment by dpwiz** [comment] 2023-09-18 09:42
> it would be awkward not to be able to round trip JSON data. It would also be awkward to have the mapping of JSON data to JS be different than the canonical mapping of JSON data to JS.

But JSON doesn't have undefined (and functions, dates).

Is there **any** serialization format that has `undefined` in its AST?

**Comment by erights** [comment] 2023-09-18 10:56
> > it would be awkward not to be able to round trip JSON data. It would also be awkward to have the mapping of JSON data to JS be different than the canonical mapping of JSON data to JS.
> 
> But JSON doesn't have undefined (and functions, dates).

Correct

> Is there **any** serialization format that has `undefined` in its AST?

OCapN ;)

In all seriousness, many serialization formats have a bottom value. If they have only one, which is typical, then aside from target language, it doesn't matter whether it is called "null" or "undefined".

For purposes of our distributed object system, we need the normal bottom to map to JS `undefined`. But we also want to be a superset of JSON and to map JSON to JS the way everyone else maps JSON to JS.

If we omit `null`, then we're not a superset of JSON, which is awkward.

**Comment by dpwiz** [comment] 2023-09-18 11:47
> OCapN ;)

Let's not be the forerunners with this particular practice :sweat_smile:

> In all seriousness, many serialization formats have a bottom value.

I think "bottom" is really confusing here, meaning different things in different contexts: subtyping vs type theory vs ..., term vs type level, and then `bottom` vs `unit` to top it off.

**Comment by dpwiz** [comment] 2023-09-18 11:54
> It would also be awkward to have the mapping of JSON data to JS be different than the canonical mapping of JSON data to JS.

`JSON.stringify` omits `undefined` values from objects and coalesces `undefined` elements to `null`. And top-level values should be objects or arrays. This is the canonical mapping. That means you can dump undefineds into JSON, but you can't get `undefined` anywhere from the wire. As a part of the codec, that is. And if something is a part of your application domain, this is something out of scope for wire-level codec.

**Comment by dpwiz** [comment] 2023-09-18 12:01
> If we omit null, then we're not a superset of JSON, which is awkward.

I see no reason to omit `null`, this is a really boring **unit** type as it gets. A null-ary constructor if you wish :woman_shrugging: 
One can encode their `()`s into it and back without losing any information.

**Comment by dpwiz** [comment] 2023-09-18 12:12
On the other hand, if I write a "proxy" in Haskell, I would have no different application type to the wire type. So, in a way, I don't care about OCapN wire codec having a special thing for `undefined` that is used to directly encode some JS application type.

The question is... why? How come some platforms have a privileged representation? Why not give a slot for C pointers, or Erlang pids, or TensorFlow (a very popular platform!) bfloat16?

**Comment by kriskowal** [comment] 2023-09-18 17:20
> The problem with using Syrup Records is that OCapN Taggeds are also encoded as Syrup Records and OCapN Tagged need to round trip as distinct from OCapN Null or Undefined.

@cwebber clarified for us on Friday that OCapN as-implemented in Guile today hotels user-defined records within a record, something like `<user-record label [...variadic-payload]>`. These user-defined records are the closest analog we have to Agoric’s tagged payloads. There are differences, but I believe we can converge. For example, the Syrup shorthand notation for null would be `<'null>` whereas `makeTagged("hunter", {target: "wumpus"})` might be represented like `<user 'hunter { target: "wumpus" }>`.

This is not to say that we should adopt the Syrup wire format, but to say that OCapN can stand on Syrup in the same way it can stand on JSON, Canonical S-expressions, or no intermediate representation at all (as in compact ordered). From the Rosetta exercise, I’m convinced that all of the options are viable for marshaling passable data.

**Comment by dpwiz** [comment] 2023-09-18 18:18
> From the Rosetta exercise, I’m convinced that all of the options are viable for marshaling passable data.
Perhaps they should be selectable just as the transports. If anything, to prevent protocol ossification.
